language: java
jdk: oraclejdk8
install: true
cache:
  directories:
  - $HOME/.m2
env:
  - MAVEN_VERSION=3.3.9
install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"
script: ./mvnw clean install -B
